include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - avoid_unnecessary_containers: true
    - avoid_web_libraries_in_flutter: true
    - no_logic_in_create_state: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - prefer_final_fields: true
    - sized_box_for_whitespace: true
    - use_full_hex_values_for_flutter_colors: true
    - use_key_in_widget_constructors: true

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
